spring:
  application:
    name: com-data-cloud-eureka
  security:
    basic:
      enabled: true
    user:
      name: data
      password: data123

eureka:
  instance:
    ip-address: localhost
    metadata-map:
      "user.name": ${spring.security.user.name}
      "user.password": ${spring.security.user.password}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://data:data123@localhost:8761/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: true
    renewal-threshold-update-interval-ms: 60000

server:
  port: 8761

logging:
  level:
    root: WARN

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS