server:
  port: 8765


spring:
  application:
    name: com-data-cloud-admin
  security:
    basic:
      enabled: true
    user:
      name: data
      password: data123
  freemarker:
    check-template-location: false


eureka:
  client:
    service-url:
      defaultZone: http://data:data123@localhost:8761/eureka/
  instance:
    metadata-map:
      "user.name": ${spring.security.user.name}
      "user.password": ${spring.security.user.password}
    healthcheck:
      enabled: true
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 3
      lease-expiration-duration-in-seconds: 6



logging:
  level:
    root: WARN

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS